### PR TITLE
add support for `and`,`or` filters with more than 2 values.

### PR DESCRIPTION
**Pull request by dakra**
allows filters like `filter = Filter(type='or', [Dimension('dim1') == v for v in list_of_values])`

### CODE REVIEW

**Comment by xvrl** [comment]
:+1:

**Comment by dakra** [comment]
Ah, didn't see the issue or the pull request.
I updated my pull request to correctly handle #42

**Comment by fjy** [comment]
@dakra can you fill out CLA if you haven't done it already?
http://druid.io/community/cla.html

**Comment by dakra** [comment]
:+1: done

**Comment by mcorbe** [comment]
@dakra: Forgot to mention that x needs to be tested as well as self in __and__ / __or__ (#42)

**Comment by dakra** [comment]
`and` or `or` are left associative so if the left filter (=`self`) is an `and` filter already and I `and` it again with *any* other filter I just add the right filter to the left filter fields.

maybe I'm missing something obvious or you meant something else?!

**Comment by mcorbe** [comment]
@dakra sorry my bad, disregard my comment. was only relevant with pull #42.

**Pull request merged**
